AllCops:
  DisabledByDefault: true

Layout:
  Enabled: true
Lint/DeprecatedClassMethods:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/DuplicateHashKey:
  Enabled: true
Lint/DuplicateMethods:
  Enabled: true
Lint/InterpolationCheck:
  Enabled: true
Lint/LiteralAsCondition:
  Enabled: true
Lint/RedundantStringCoercion:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/UnderscorePrefixedVariableName:
  Enabled: true
Lint/UnusedBlockArgument:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true
Style/AndOr:
  Enabled: true
Style/Documentation:
  Enabled: true
Style/DocumentationMethod:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: true
Style/HashSyntax:
  Enabled: true
Style/Next:
  Enabled: true
Style/NilComparison:
  Enabled: true
Style/RedundantParentheses:
  Enabled: true
Style/RedundantSelf:
  Enabled: true
Style/ReturnNil:
  Enabled: true
Style/SelfAssignment:
  Enabled: true
Style/StringLiterals:
  Enabled: true
Style/StringLiteralsInInterpolation:
  Enabled: true