Layout/EndOfLine:
  Enabled: false
Metrics/LineLength:
  AutoCorrect: false
  Enabled: false
Layout/RescueEnsureAlignment:
  AutoCorrect: true
Style/FrozenStringLiteralComment:
  AutoCorrect: true
# Enable the cops below when rubocop is upgraded
#Style/HashEachMethods:
#  Enabled: true
#Style/HashTransformKeys:
#  Enabled: true
#Style/HashTransformValues:
#  Enabled: true