# frozen_string_literal: true

require_relative '../resources/minitest_helper'
require 'openstudio'
require 'openstudio/ruleset/ShowRunnerOutput'
require 'minitest/autorun'
require 'fileutils'
require_relative '../measure.rb'
require_relative '../resources/util.rb'
require 'schematron-nokogiri'

class HPXMLtoOpenStudioSchematronTest < MiniTest::Test
  def before_setup
    @root_path = File.absolute_path(File.join(File.dirname(__FILE__), '..', '..'))
    @tmp_output_path = File.join(@root_path, 'workflow', 'sample_files', 'tmp_output')
    FileUtils.mkdir_p(@tmp_output_path)
    @tmp_hpxml_path = File.join(@tmp_output_path, 'tmp.xml')
  end
  
  def after_teardown
    FileUtils.rm_rf(@tmp_output_path)
  end

  def get_hpxml_file_name(key)
    if key.include? '/HPXML/Building/BuildingDetails/BuildingSummary/Site/extension/Neighbors'
      return 'base-misc-neighbor-shading.xml'
    elsif key == '/HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor[ExteriorAdjacentTo[text()="other housing unit"]]/extension/OtherSpaceAboveOrBelow'
      return 'base-enclosure-other-housing-unit.xml'
    elsif key.include? '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump'
      return 'base-hvac-air-to-air-heat-pump-1-speed.xml'
    elsif key.include? '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl'
      return 'base-hvac-programmable-thermostat.xml'
    elsif key.include? '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution[DistributionSystemType[Other="DSE"]]'
      return 'base-hvac-dse.xml'
    elsif key.include? '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true"]' or 
      key.include? '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true" and FanType="heat recovery ventilator"]'
      return 'base-mechvent-hrv.xml'
    elsif key.include? '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true" and FanType="energy recovery ventilator"]'
      return 'base-mechvent-erv.xml'
    elsif key.include? '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true" and FanType="central fan integrated supply"]'
      return 'base-mechvent-cfis.xml'
    elsif key.include? '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForLocalVentilation="true" and FanLocation="kitchen"]' or
      key.include? '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForLocalVentilation="true" and FanLocation="bath"]'
      return 'base-mechvent-bath-kitchen-fans.xml'
    elsif key.include? '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForSeasonalCoolingLoadReduction="true"]'
      return 'base-misc-whole-house-fan.xml'
    elsif key.include? '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/Overhangs'
      return 'base-enclosure-overhangs.xml'
    elsif key.include? '/HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight'
      return 'base-enclosure-skylights.xml'
    else
      return 'base.xml'
    end
  end

  def test_valid_sample_files
    sample_files_dir = File.absolute_path(File.join(@root_path, 'workflow', 'sample_files'))
    hpxmls = []
    Dir["#{sample_files_dir}/*.xml"].sort.each do |xml|
      hpxmls << File.absolute_path(xml)
    end
    hpxmls.each do |hpxml|
      _test_schematron_validation(hpxml)
    end
  end

  def test_invalid_files_schematron_validation
    # TODO: Need to add more test cases
    expected_error_msgs = { '/HPXML/XMLTransactionHeaderInformation/XMLType' => "element 'XMLType' is REQUIRED",
                            '/HPXML/XMLTransactionHeaderInformation/XMLGeneratedBy' => "element 'XMLGeneratedBy' is REQUIRED",
                            '/HPXML/XMLTransactionHeaderInformation/CreatedDateAndTime' => "element 'CreatedDateAndTime' is REQUIRED",
                            '/HPXML/XMLTransactionHeaderInformation/Transaction' => "element 'Transaction' is REQUIRED",
                            '/HPXML/Building' => "element 'Building' is REQUIRED",
                            '/HPXML/Building/BuildingID' => "element 'Building/BuildingID' is REQUIRED",
                            '/HPXML/Building/ProjectStatus/EventType' => "element 'Building/ProjectStatus/EventType' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction' => "element 'BuildingConstruction' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/ClimateandRiskZones/WeatherStation' => "element 'WeatherStation' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement/HousePressure' => "Air leakage must be provided in one of three ways: (a) nACH (natural air changes per hour), (b) ACH50 (air changes per hour at 50Pa), or (c) CFM50 (cubic feet per minute at 50Pa)",
                            '/HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement/BuildingAirLeakage/UnitofMeasure' => "Air leakage must be provided in one of three ways: (a) nACH (natural air changes per hour), (b) ACH50 (air changes per hour at 50Pa), or (c) CFM50 (cubic feet per minute at 50Pa)",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall' => "the number of element 'Walls/Wall' MUST be greater than or equal to 1",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction/NumberofConditionedFloors' => "element 'NumberofConditionedFloors' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction/NumberofConditionedFloorsAboveGrade' => "element 'NumberofConditionedFloorsAboveGrade' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction/NumberofBedrooms' => "element 'NumberofBedrooms' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction/ConditionedFloorArea' => "element 'ConditionedFloorArea' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction/ConditionedBuildingVolume' => "either element 'ConditionedBuildingVolume' or element 'AverageCeilingHeight' must be provided",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/Site/extension/Neighbors/NeighborBuilding' => "element 'NeighborBuilding' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/Site/extension/Neighbors/NeighborBuilding/Azimuth' => "element 'Azimuth' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/Site/extension/Neighbors/NeighborBuilding/Distance' => "element 'Distance' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/ClimateandRiskZones/ClimateZoneIECC/Year' => "element 'Year' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/ClimateandRiskZones/ClimateZoneIECC/ClimateZone' => "element 'ClimateZone' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/ClimateandRiskZones/WeatherStation/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/ClimateandRiskZones/WeatherStation/Name' => "element 'Name' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/ClimateandRiskZones/WeatherStation/WMO' => "either element 'WMO' or element 'extension/EPWFilePath' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement[number(HousePressure)=50 and BuildingAirLeakage/UnitofMeasure[text()="ACH" or text()="CFM"]]/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement[number(HousePressure)=50 and BuildingAirLeakage/UnitofMeasure[text()="ACH" or text()="CFM"]]/BuildingAirLeakage/AirLeakage' => "element 'BuildingAirLeakage/AirLeakage' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/InteriorAdjacentTo' => "element 'InteriorAdjacentTo' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/Area' => "element 'Area' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/SolarAbsorptance' => "element 'SolarAbsorptance' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/Emittance' => "element 'Emittance' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/Pitch' => "element 'Pitch' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/RadiantBarrier' => "element 'RadiantBarrier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/Insulation/SystemIdentifier' => "element 'Insulation/SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/Insulation/AssemblyEffectiveRValue' => "element 'Insulation/AssemblyEffectiveRValue' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/ExteriorAdjacentTo' => "element 'ExteriorAdjacentTo' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/InteriorAdjacentTo' => "element 'InteriorAdjacentTo' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/WallType/WoodStud' => "element 'WallType' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/Area' => "element 'Area' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/SolarAbsorptance' => "element 'SolarAbsorptance' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/Emittance' => "element 'Emittance' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/Insulation/SystemIdentifier' => "element 'Insulation/SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/Insulation/AssemblyEffectiveRValue' => "element 'Insulation/AssemblyEffectiveRValue' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/ExteriorAdjacentTo' => "element 'ExteriorAdjacentTo' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/InteriorAdjacentTo' => "element 'InteriorAdjacentTo' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/Area' => "element 'Area' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/SolarAbsorptance' => "element 'SolarAbsorptance' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/Emittance' => "element 'Emittance' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/Insulation/SystemIdentifier' => "element 'Insulation/SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/Insulation/AssemblyEffectiveRValue' => "element 'Insulation/AssemblyEffectiveRValue' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/ExteriorAdjacentTo' => "element 'ExteriorAdjacentTo' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/InteriorAdjacentTo' => "element 'InteriorAdjacentTo' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Height' => "element 'Height' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Area' => "element 'Area' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Thickness' => "element 'Thickness' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/DepthBelowGrade' => "element 'DepthBelowGrade' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/SystemIdentifier' => "element 'Insulation/SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - interior"]' => "element 'Insulation/Layer[InstallationType='continuous - interior']' or 'Insulation/AssemblyEffectiveRValue' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - exterior"]' => "element 'Insulation/Layer[InstallationType='continuous - exterior']' or 'Insulation/AssemblyEffectiveRValue' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - interior"]/NominalRValue' => "element 'NominalRValue' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - interior"]/extension/DistanceToTopOfInsulation' => "element 'extension/DistanceToTopOfInsulation' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - interior"]/extension/DistanceToBottomOfInsulation' => "element 'extension/DistanceToBottomOfInsulation' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - exterior"]/NominalRValue' => "element 'NominalRValue' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - exterior"]/extension/DistanceToTopOfInsulation' => "element 'extension/DistanceToTopOfInsulation' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - exterior"]/extension/DistanceToBottomOfInsulation' => "element 'extension/DistanceToBottomOfInsulation' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor/ExteriorAdjacentTo' => "element 'ExteriorAdjacentTo' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor/InteriorAdjacentTo' => "element 'InteriorAdjacentTo' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor/Area' => "element 'Area' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor/Insulation/SystemIdentifier' => "element 'Insulation/SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor/Insulation/AssemblyEffectiveRValue' => "element 'Insulation/AssemblyEffectiveRValue' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor[ExteriorAdjacentTo[text()="other housing unit"]]/extension/OtherSpaceAboveOrBelow' => "element 'extension/OtherSpaceAboveOrBelow' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/InteriorAdjacentTo' => "element 'InteriorAdjacentTo' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/Area' => "element 'Area' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/Thickness' => "element 'Thickness' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/ExposedPerimeter' => "element 'ExposedPerimeter' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/PerimeterInsulationDepth' => "element 'PerimeterInsulationDepth' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/UnderSlabInsulationWidth' => "element 'UnderSlabInsulationWidth' or 'UnderSlabInsulationSpansEntireSlab[text()=\"true\"]' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/PerimeterInsulation/SystemIdentifier' => "element 'PerimeterInsulation/SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/PerimeterInsulation/Layer[InstallationType="continuous"]/NominalRValue' => "element 'PerimeterInsulation/Layer[InstallationType=\"continuous\"]/NominalRValue' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/UnderSlabInsulation/SystemIdentifier' => "element 'UnderSlabInsulation/SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/UnderSlabInsulation/Layer[InstallationType="continuous"]/NominalRValue' => "element 'UnderSlabInsulation/Layer[InstallationType=\"continuous\"]/NominalRValue' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/extension/CarpetFraction' => "element 'extension/CarpetFraction' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/extension/CarpetRValue' => "element 'extension/CarpetRValue' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/Area' => "element 'Area' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/Azimuth' => "element 'Azimuth' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/UFactor' => "element 'UFactor' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/SHGC' => "element 'SHGC' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/AttachedToWall' => "element 'AttachedToWall' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/Overhangs/Depth' => "element 'Depth' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/Overhangs/DistanceToTopOfWindow' => "element 'DistanceToTopOfWindow' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/Overhangs/DistanceToBottomOfWindow' => "element 'DistanceToBottomOfWindow' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight/Area' => "element 'Area' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight/Azimuth' => "element 'Azimuth' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight/UFactor' => "element 'UFactor' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight/SHGC' => "element 'SHGC' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight/AttachedToRoof' => "element 'AttachedToRoof' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl' => "element 'HVACControl' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem/HeatingSystemType/Furnace' => "element 'HeatingSystemType' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem/FractionHeatLoadServed' => "element 'FractionHeatLoadServed' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution[DistributionSystemType/AirDistribution]' => "the number of element DistributionSystemType/AirDistribution or DistributionSystemType[Other='DSE'] MUST be greater than or equal to 1",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem[HeatingSystemType/Furnace]/DistributionSystem' => "element 'DistributionSystem' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem[HeatingSystemType/Furnace]/HeatingSystemFuel' => "element 'HeatingSystemFuel' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem[HeatingSystemType/Furnace]/AnnualHeatingEfficiency[Units="AFUE"]/Value' => "element 'AnnualHeatingEfficiency[Units='AFUE']/Value' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType="central air conditioner"]/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType="central air conditioner"]/CoolingSystemType[text()="central air conditioner" or text()="room air conditioner" or text()="evaporative cooler"]' => "element 'CoolingSystemType[text()='central air conditioner' or text()='room air conditioner' or text()='evaporative cooler']' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType="central air conditioner"]/CoolingSystemFuel[text()="electricity"]' => "element 'CoolingSystemFuel[text()='electricity']' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType="central air conditioner"]/FractionCoolLoadServed' => "element 'FractionCoolLoadServed' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution[DistributionSystemType/AirDistribution | DistributionSystemType[Other="DSE"]]' => "element '../../HVACDistribution[DistributionSystemType/AirDistribution | DistributionSystemType[Other='DSE']]' MUST be greater than or equal to 1",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType="central air conditioner"]/DistributionSystem' => "element 'DistributionSystem' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType="central air conditioner"]/CompressorType[text()="single stage" or text()="two stage" or text()="variable speed"]' => "element '[not(CompressorType)] | CompressorType[text()='single stage' or text()='two stage' or text()='variable speed']' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType="central air conditioner"]/AnnualCoolingEfficiency[Units="SEER"]/Value' => "element 'AnnualCoolingEfficiency[Units='SEER']/Value' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump/HeatPumpType' => "element 'HeatPumpType[text()='air-to-air' or text()='mini-split' or text()='ground-to-air']' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump/HeatPumpFuel' => "element 'HeatPumpFuel[text()='electricity']' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump/FractionHeatLoadServed' => "element 'FractionHeatLoadServed' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump/FractionCoolLoadServed' => "element 'FractionCoolLoadServed' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump[HeatPumpType="air-to-air"]/DistributionSystem' => "element 'DistributionSystem' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump[HeatPumpType="air-to-air"]/AnnualCoolingEfficiency[Units="SEER"]/Value' => "element 'AnnualCoolingEfficiency[Units='SEER']/Value' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump[HeatPumpType="air-to-air"]/AnnualHeatingEfficiency[Units="HSPF"]/Value' => "element 'AnnualHeatingEfficiency[Units='HSPF']/Value' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl/SetpointTempHeatingSeason' => "element 'SetpointTempHeatingSeason' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl/SetpointTempCoolingSeason' => "element 'SetpointTempCoolingSeason' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl[SetbackTempHeatingSeason]/TotalSetbackHoursperWeekHeating' => "element 'TotalSetbackHoursperWeekHeating' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl[SetbackTempHeatingSeason]/extension/SetbackStartHourHeating' => "element 'extension/SetbackStartHourHeating' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl[SetupTempCoolingSeason]/TotalSetupHoursperWeekCooling' => "element 'TotalSetupHoursperWeekCooling' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl[SetupTempCoolingSeason]/extension/SetupStartHourCooling' => "element 'extension/SetupStartHourCooling' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/DistributionSystemType/AirDistribution' => "element 'DistributionSystemType/AirDistribution | DistributionSystemType/HydronicDistribution | DistributionSystemType[Other='DSE']' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/ConditionedFloorAreaServed' => "element '../../ConditionedFloorAreaServed' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/DistributionSystemType/AirDistribution/DuctLeakageMeasurement[DuctType="supply"]/DuctLeakage[(Units="CFM25" or Units="Percent") and TotalOrToOutside="to outside"]/Value' => "element 'DuctLeakageMeasurement[DuctType='supply']/DuctLeakage[(Units='CFM25' or Units='Percent') and TotalOrToOutside='to outside']/Value' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution[DistributionSystemType[Other="DSE"]]/AnnualHeatingDistributionSystemEfficiency | AnnualCoolingDistributionSystemEfficiency' => "element 'AnnualHeatingDistributionSystemEfficiency | AnnualCoolingDistributionSystemEfficiency' MUST be greater than or equal to 1",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/DistributionSystemType/AirDistribution/Ducts[DuctType="supply" or DuctType="return"]/DuctInsulationRValue' => "element 'DuctInsulationRValue' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/DistributionSystemType/AirDistribution/Ducts[DuctType="supply" or DuctType="return"]/DuctSurfaceArea | DuctLocation[text()="living space" or text()="basement - conditioned" or text()="basement - unconditioned" or text()="crawlspace - vented" or text()="crawlspace - unvented" or text()="attic - vented" or text()="attic - unvented" or text()="garage" or text()="exterior wall" or text()="under slab" or text()="roof deck" or text()="outside" or text()="other housing unit" or text()="other heated space" or text()="other multifamily buffer space" or text()="other non-freezing space"]' => "both element 'DuctSurfaceArea' and 'DuctLocation' MUST be either blank or provided",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true"]/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true"]/FanType[text()="energy recovery ventilator" or text()="heat recovery ventilator" or text()="exhaust only" or text()="supply only" or text()="balanced" or text()="central fan integrated supply"]' => "element 'FanType' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true"]/TestedFlowRate' => "element 'TestedFlowRate | RatedFlowRate' MUST be greater than or equal to 1",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true"]/HoursInOperation' => "element 'HoursInOperation' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true"]/FanPower' => "element 'FanPower' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true" and FanType="heat recovery ventilator"]/SensibleRecoveryEfficiency | AdjustedSensibleRecoveryEfficiency' => "element 'SensibleRecoveryEfficiency | AdjustedSensibleRecoveryEfficiency' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true" and FanType="energy recovery ventilator"]/TotalRecoveryEfficiency | AdjustedTotalRecoveryEfficiency' => "element 'TotalRecoveryEfficiency | AdjustedTotalRecoveryEfficiency' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true" and FanType="energy recovery ventilator"]/SensibleRecoveryEfficiency | AdjustedSensibleRecoveryEfficiency' => "element 'SensibleRecoveryEfficiency | AdjustedSensibleRecoveryEfficiency' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true" and FanType="central fan integrated supply"]/AttachedToHVACDistributionSystem' => "element 'AttachedToHVACDistributionSystem' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForLocalVentilation="true" and FanLocation="kitchen"]/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForLocalVentilation="true" and FanLocation="bath"]/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForSeasonalCoolingLoadReduction="true"]/SystemIdentifier' => "element 'SystemIdentifier' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForSeasonalCoolingLoadReduction="true"]/RatedFlowRate' => "element 'RatedFlowRate' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForSeasonalCoolingLoadReduction="true"]/FanPower' => "element 'FanPower' is REQUIRED",
                          }
    
    expected_error_msgs.each do |key, value|
      hpxml_name = get_hpxml_file_name(key)
      hpxml = HPXML.new(hpxml_path: File.join(@root_path, 'workflow', 'sample_files', hpxml_name))
      hpxml_doc = hpxml.to_oga()
      XMLHelper.delete_element(hpxml_doc, key)
      XMLHelper.write_file(hpxml_doc, @tmp_hpxml_path)
      _test_schematron_validation(@tmp_hpxml_path, value)
    end
  end

  def test_invalid_files_validator_validation
    # TODO: Need to add more test cases
    expected_error_msgs = { '/HPXML/XMLTransactionHeaderInformation/XMLType' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/XMLTransactionHeaderInformation/XMLType",
                            '/HPXML/XMLTransactionHeaderInformation/XMLGeneratedBy' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/XMLTransactionHeaderInformation/XMLGeneratedBy",
                            '/HPXML/XMLTransactionHeaderInformation/CreatedDateAndTime' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/XMLTransactionHeaderInformation/CreatedDateAndTime",
                            '/HPXML/XMLTransactionHeaderInformation/Transaction' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/XMLTransactionHeaderInformation/Transaction",
                            '/HPXML/Building' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building",
                            '/HPXML/Building/BuildingID' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingID",
                            '/HPXML/Building/ProjectStatus/EventType' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/ProjectStatus/EventType",
                            '/HPXML/Building/BuildingDetails/ClimateandRiskZones/WeatherStation' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/ClimateandRiskZones/WeatherStation",
                            '/HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement/HousePressure' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement[number(HousePressure)=50 and BuildingAirLeakage/UnitofMeasure[text()=\"ACH\" or text()=\"CFM\"]] | /HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement[BuildingAirLeakage/UnitofMeasure[text()=\"ACHnatural\"]]",
                            '/HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement/BuildingAirLeakage/UnitofMeasure' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement[number(HousePressure)=50 and BuildingAirLeakage/UnitofMeasure[text()=\"ACH\" or text()=\"CFM\"]] | /HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement[BuildingAirLeakage/UnitofMeasure[text()=\"ACHnatural\"]]",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall' => "Expected 1 or more element(s) but found 0 elements for xpath: /HPXML/Building/BuildingDetails/Enclosure/Walls/Wall",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction/NumberofConditionedFloors' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction: NumberofConditionedFloors",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction/NumberofConditionedFloorsAboveGrade' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction: NumberofConditionedFloorsAboveGrade",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction/NumberofBedrooms' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction: NumberofBedrooms",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction/ConditionedFloorArea' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction: ConditionedFloorArea",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction/ConditionedBuildingVolume' => "Expected 1 or more element(s) but found 0 elements for xpath: /HPXML/Building/BuildingDetails/BuildingSummary/BuildingConstruction: ConditionedBuildingVolume | AverageCeilingHeight",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/Site/extension/Neighbors/NeighborBuilding' => "Expected 1 or more element(s) but found 0 elements for xpath: /HPXML/Building/BuildingDetails/BuildingSummary/Site/extension/Neighbors: NeighborBuilding",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/Site/extension/Neighbors/NeighborBuilding/Azimuth' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/BuildingSummary/Site/extension/Neighbors/NeighborBuilding: Azimuth",
                            '/HPXML/Building/BuildingDetails/BuildingSummary/Site/extension/Neighbors/NeighborBuilding/Distance' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/BuildingSummary/Site/extension/Neighbors/NeighborBuilding: Distance",
                            '/HPXML/Building/BuildingDetails/ClimateandRiskZones/ClimateZoneIECC/Year' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/ClimateandRiskZones/ClimateZoneIECC: Year",
                            '/HPXML/Building/BuildingDetails/ClimateandRiskZones/ClimateZoneIECC/ClimateZone' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/ClimateandRiskZones/ClimateZoneIECC: ClimateZone[text()=\"1A\" or text()=\"1B\" or text()=\"1C\" or text()=\"2A\" or text()=\"2B\" or text()=\"2C\" or text()=\"3A\" or text()=\"3B\" or text()=\"3C\" or text()=\"4A\" or text()=\"4B\" or text()=\"4C\" or text()=\"5A\" or text()=\"5B\" or text()=\"5C\" or text()=\"6A\" or text()=\"6B\" or text()=\"6C\" or text()=\"7\" or text()=\"8\"]",
                            '/HPXML/Building/BuildingDetails/ClimateandRiskZones/WeatherStation/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/ClimateandRiskZones/WeatherStation: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/ClimateandRiskZones/WeatherStation/Name' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/ClimateandRiskZones/WeatherStation: Name",
                            '/HPXML/Building/BuildingDetails/ClimateandRiskZones/WeatherStation/WMO' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/ClimateandRiskZones/WeatherStation: WMO | extension/EPWFilePath",
                            '/HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement[number(HousePressure)=50 and BuildingAirLeakage/UnitofMeasure[text()="ACH" or text()="CFM"]]/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement[number(HousePressure)=50 and BuildingAirLeakage/UnitofMeasure[text()=\"ACH\" or text()=\"CFM\"]] | /HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement[BuildingAirLeakage/UnitofMeasure[text()=\"ACHnatural\"]]: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement[number(HousePressure)=50 and BuildingAirLeakage/UnitofMeasure[text()="ACH" or text()="CFM"]]/BuildingAirLeakage/AirLeakage' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement[number(HousePressure)=50 and BuildingAirLeakage/UnitofMeasure[text()=\"ACH\" or text()=\"CFM\"]] | /HPXML/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement[BuildingAirLeakage/UnitofMeasure[text()=\"ACHnatural\"]]: BuildingAirLeakage/AirLeakage",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/InteriorAdjacentTo' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof: InteriorAdjacentTo[text()=\"attic - vented\" or text()=\"attic - unvented\" or text()=\"living space\" or text()=\"garage\"]",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/Area' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof: Area",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/SolarAbsorptance' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof: SolarAbsorptance",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/Emittance' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof: Emittance",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/Pitch' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof: Pitch",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/RadiantBarrier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof: RadiantBarrier",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/Insulation/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof: Insulation/SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof/Insulation/AssemblyEffectiveRValue' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Roofs/Roof: Insulation/AssemblyEffectiveRValue",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Walls/Wall: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/ExteriorAdjacentTo' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Walls/Wall: ExteriorAdjacentTo[text()=\"outside\" or text()=\"attic - vented\" or text()=\"attic - unvented\" or text()=\"basement - conditioned\" or text()=\"basement - unconditioned\" or text()=\"crawlspace - vented\" or text()=\"crawlspace - unvented\" or text()=\"garage\" or text()=\"other housing unit\" or text()=\"other heated space\" or text()=\"other multifamily buffer space\" or text()=\"other non-freezing space\"]",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/InteriorAdjacentTo' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Walls/Wall: InteriorAdjacentTo[text()=\"living space\" or text()=\"attic - vented\" or text()=\"attic - unvented\" or text()=\"basement - conditioned\" or text()=\"basement - unconditioned\" or text()=\"crawlspace - vented\" or text()=\"crawlspace - unvented\" or text()=\"garage\"]",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/WallType/WoodStud' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Walls/Wall: WallType[WoodStud | DoubleWoodStud | ConcreteMasonryUnit | StructurallyInsulatedPanel | InsulatedConcreteForms | SteelFrame | SolidConcrete | StructuralBrick | StrawBale | Stone | LogWall]",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/Area' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Walls/Wall: Area",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/SolarAbsorptance' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Walls/Wall: SolarAbsorptance",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/Emittance' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Walls/Wall: Emittance",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/Insulation/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Walls/Wall: Insulation/SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/Walls/Wall/Insulation/AssemblyEffectiveRValue' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Walls/Wall: Insulation/AssemblyEffectiveRValue",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/ExteriorAdjacentTo' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist: ExteriorAdjacentTo[text()=\"outside\" or text()=\"attic - vented\" or text()=\"attic - unvented\" or text()=\"basement - conditioned\" or text()=\"basement - unconditioned\" or text()=\"crawlspace - vented\" or text()=\"crawlspace - unvented\" or text()=\"garage\" or text()=\"other housing unit\" or text()=\"other heated space\" or text()=\"other multifamily buffer space\" or text()=\"other non-freezing space\"]",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/InteriorAdjacentTo' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist: InteriorAdjacentTo[text()=\"living space\" or text()=\"attic - vented\" or text()=\"attic - unvented\" or text()=\"basement - conditioned\" or text()=\"basement - unconditioned\" or text()=\"crawlspace - vented\" or text()=\"crawlspace - unvented\" or text()=\"garage\"]",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/Area' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist: Area",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/SolarAbsorptance' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist: SolarAbsorptance",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/Emittance' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist: Emittance",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/Insulation/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist: Insulation/SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/Insulation/AssemblyEffectiveRValue' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/RimJoists/RimJoist: Insulation/AssemblyEffectiveRValue",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/ExteriorAdjacentTo' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall: ExteriorAdjacentTo[text()=\"ground\" or text()=\"basement - conditioned\" or text()=\"basement - unconditioned\" or text()=\"crawlspace - vented\" or text()=\"crawlspace - unvented\" or text()=\"garage\" or text()=\"other housing unit\" or text()=\"other heated space\" or text()=\"other multifamily buffer space\" or text()=\"other non-freezing space\"]",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/InteriorAdjacentTo' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall: InteriorAdjacentTo[text()=\"basement - conditioned\" or text()=\"basement - unconditioned\" or text()=\"crawlspace - vented\" or text()=\"crawlspace - unvented\" or text()=\"garage\"]",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Height' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall: Height",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Area' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall: Area",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Thickness' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall: Thickness",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/DepthBelowGrade' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall: DepthBelowGrade",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall: Insulation/SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - interior"]' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall: Insulation/Layer[InstallationType=\"continuous - interior\"] | Insulation/AssemblyEffectiveRValue",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - exterior"]' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall: Insulation/Layer[InstallationType=\"continuous - exterior\"] | Insulation/AssemblyEffectiveRValue",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - interior"]/NominalRValue' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType=\"continuous - exterior\" or InstallationType=\"continuous - interior\"]: NominalRValue",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - interior"]/extension/DistanceToTopOfInsulation' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType=\"continuous - exterior\" or InstallationType=\"continuous - interior\"]: extension/DistanceToTopOfInsulation",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - interior"]/extension/DistanceToBottomOfInsulation' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType=\"continuous - exterior\" or InstallationType=\"continuous - interior\"]: extension/DistanceToBottomOfInsulation",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - exterior"]/NominalRValue' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType=\"continuous - exterior\" or InstallationType=\"continuous - interior\"]: NominalRValue",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - exterior"]/extension/DistanceToTopOfInsulation' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType=\"continuous - exterior\" or InstallationType=\"continuous - interior\"]: extension/DistanceToTopOfInsulation",
                            '/HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType="continuous - exterior"]/extension/DistanceToBottomOfInsulation' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/Insulation/Layer[InstallationType=\"continuous - exterior\" or InstallationType=\"continuous - interior\"]: extension/DistanceToBottomOfInsulation",
                            '/HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor/ExteriorAdjacentTo' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor: ExteriorAdjacentTo[text()=\"outside\" or text()=\"attic - vented\" or text()=\"attic - unvented\" or text()=\"basement - conditioned\" or text()=\"basement - unconditioned\" or text()=\"crawlspace - vented\" or text()=\"crawlspace - unvented\" or text()=\"garage\" or text()=\"other housing unit\" or text()=\"other heated space\" or text()=\"other multifamily buffer space\" or text()=\"other non-freezing space\"]",
                            '/HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor/InteriorAdjacentTo' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor: InteriorAdjacentTo[text()=\"living space\" or text()=\"attic - vented\" or text()=\"attic - unvented\" or text()=\"basement - conditioned\" or text()=\"basement - unconditioned\" or text()=\"crawlspace - vented\" or text()=\"crawlspace - unvented\" or text()=\"garage\"]",
                            '/HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor/Area' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor: Area",
                            '/HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor/Insulation/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor: Insulation/SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor/Insulation/AssemblyEffectiveRValue' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor: Insulation/AssemblyEffectiveRValue",
                            '/HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor[ExteriorAdjacentTo[text()="other housing unit"]]/extension/OtherSpaceAboveOrBelow' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor[ExteriorAdjacentTo[text()=\"other housing unit\" or text()=\"other heated space\" or text()=\"other multifamily buffer space\" or text()=\"other non-freezing space\"]]: extension/OtherSpaceAboveOrBelow[text()=\"above\" or text()=\"below\"]",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/InteriorAdjacentTo' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab: InteriorAdjacentTo[text()=\"living space\" or text()=\"basement - conditioned\" or text()=\"basement - unconditioned\" or text()=\"crawlspace - vented\" or text()=\"crawlspace - unvented\" or text()=\"garage\"]",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/Area' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab: Area",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/Thickness' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab: Thickness",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/ExposedPerimeter' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab: ExposedPerimeter",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/PerimeterInsulationDepth' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab: PerimeterInsulationDepth",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/UnderSlabInsulationWidth' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab: UnderSlabInsulationWidth | UnderSlabInsulationSpansEntireSlab[text()=\"true\"]",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/PerimeterInsulation/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab: PerimeterInsulation/SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/PerimeterInsulation/Layer[InstallationType="continuous"]/NominalRValue' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab: PerimeterInsulation/Layer[InstallationType=\"continuous\"]/NominalRValue",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/UnderSlabInsulation/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab: UnderSlabInsulation/SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/UnderSlabInsulation/Layer[InstallationType="continuous"]/NominalRValue' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab: UnderSlabInsulation/Layer[InstallationType=\"continuous\"]/NominalRValue",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/extension/CarpetFraction' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab: extension/CarpetFraction",
                            '/HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab/extension/CarpetRValue' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Slabs/Slab: extension/CarpetRValue",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Windows/Window: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/Area' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Windows/Window: Area",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/Azimuth' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Windows/Window: Azimuth",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/UFactor' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Windows/Window: UFactor",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/SHGC' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Windows/Window: SHGC",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/AttachedToWall' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Windows/Window: AttachedToWall",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/Overhangs/Depth' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Windows/Window/Overhangs: Depth",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/Overhangs/DistanceToTopOfWindow' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Windows/Window/Overhangs: DistanceToTopOfWindow",
                            '/HPXML/Building/BuildingDetails/Enclosure/Windows/Window/Overhangs/DistanceToBottomOfWindow' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Windows/Window/Overhangs: DistanceToBottomOfWindow",
                            '/HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight/Area' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight: Area",
                            '/HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight/Azimuth' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight: Azimuth",
                            '/HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight/UFactor' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight: UFactor",
                            '/HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight/SHGC' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight: SHGC",
                            '/HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight/AttachedToRoof' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Enclosure/Skylights/Skylight: AttachedToRoof",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem: ../../HVACControl",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem/HeatingSystemType/Furnace' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem: HeatingSystemType[ElectricResistance | Furnace | WallFurnace | FloorFurnace | Boiler | Stove | PortableHeater | Fireplace]",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem/FractionHeatLoadServed' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem: FractionHeatLoadServed",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution[DistributionSystemType/AirDistribution]' => "Expected 1 or more element(s) but found 0 elements for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem[HeatingSystemType/Furnace]: ../../HVACDistribution[DistributionSystemType/AirDistribution | DistributionSystemType[Other=\"DSE\"]]",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem[HeatingSystemType/Furnace]/DistributionSystem' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem[HeatingSystemType/Furnace]: DistributionSystem",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem[HeatingSystemType/Furnace]/HeatingSystemFuel' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem[HeatingSystemType/Furnace]: HeatingSystemFuel[text()=\"natural gas\" or text()=\"fuel oil\" or text()=\"propane\" or text()=\"electricity\" or text()=\"wood\" or text()=\"wood pellets\"]",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem[HeatingSystemType/Furnace]/AnnualHeatingEfficiency[Units="AFUE"]/Value' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem[HeatingSystemType/Furnace]: AnnualHeatingEfficiency[Units=\"AFUE\"]/Value",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType="central air conditioner"]/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType="central air conditioner"]/CoolingSystemType[text()="central air conditioner" or text()="room air conditioner" or text()="evaporative cooler"]' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem: CoolingSystemType[text()=\"central air conditioner\" or text()=\"room air conditioner\" or text()=\"evaporative cooler\"]",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType="central air conditioner"]/CoolingSystemFuel[text()="electricity"]' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem: CoolingSystemFuel[text()=\"electricity\"]",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType="central air conditioner"]/FractionCoolLoadServed' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem: FractionCoolLoadServed",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution[DistributionSystemType/AirDistribution | DistributionSystemType[Other="DSE"]]' => "Expected 1 or more element(s) but found 0 elements for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem[HeatingSystemType/Furnace]: ../../HVACDistribution[DistributionSystemType/AirDistribution | DistributionSystemType[Other=\"DSE\"]]",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType="central air conditioner"]/DistributionSystem' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType=\"central air conditioner\"]: DistributionSystem",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType="central air conditioner"]/CompressorType[text()="single stage" or text()="two stage" or text()="variable speed"]' => "element '[not(CompressorType)] | CompressorType[text()='single stage' or text()='two stage' or text()='variable speed']' is REQUIRED",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType="central air conditioner"]/AnnualCoolingEfficiency[Units="SEER"]/Value' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType=\"central air conditioner\"]: AnnualCoolingEfficiency[Units=\"SEER\"]/Value",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump/HeatPumpType' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump: HeatPumpType[text()=\"air-to-air\" or text()=\"mini-split\" or text()=\"ground-to-air\"]",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump/HeatPumpFuel' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump: HeatPumpFuel[text()=\"electricity\"]",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump/FractionHeatLoadServed' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump: FractionHeatLoadServed",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump/FractionCoolLoadServed' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump: FractionCoolLoadServed",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump[HeatPumpType="air-to-air"]/DistributionSystem' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump[HeatPumpType=\"air-to-air\"]: DistributionSystem",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump[HeatPumpType="air-to-air"]/AnnualCoolingEfficiency[Units="SEER"]/Value' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump[HeatPumpType=\"air-to-air\"]: AnnualCoolingEfficiency[Units=\"SEER\"]/Value",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump[HeatPumpType="air-to-air"]/AnnualHeatingEfficiency[Units="HSPF"]/Value' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump[HeatPumpType=\"air-to-air\"]: AnnualHeatingEfficiency[Units=\"HSPF\"]/Value",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl/SetpointTempHeatingSeason' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl: SetpointTempHeatingSeason",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl/SetpointTempCoolingSeason' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl: SetpointTempCoolingSeason",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl[SetbackTempHeatingSeason]/TotalSetbackHoursperWeekHeating' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl[SetbackTempHeatingSeason]: TotalSetbackHoursperWeekHeating",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl[SetbackTempHeatingSeason]/extension/SetbackStartHourHeating' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl[SetbackTempHeatingSeason]: extension/SetbackStartHourHeating",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl[SetupTempCoolingSeason]/TotalSetupHoursperWeekCooling' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl[SetupTempCoolingSeason]: TotalSetupHoursperWeekCooling",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl[SetupTempCoolingSeason]/extension/SetupStartHourCooling' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACControl[SetupTempCoolingSeason]: extension/SetupStartHourCooling",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/DistributionSystemType/AirDistribution' => "Expected 1 or more element(s) but found 0 elements for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem[HeatingSystemType/Furnace]: ../../HVACDistribution[DistributionSystemType/AirDistribution | DistributionSystemType[Other=\"DSE\"]]",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/ConditionedFloorAreaServed' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/DistributionSystemType/AirDistribution: ../../ConditionedFloorAreaServed",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/DistributionSystemType/AirDistribution/DuctLeakageMeasurement[DuctType="supply"]/DuctLeakage[(Units="CFM25" or Units="Percent") and TotalOrToOutside="to outside"]/Value' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/DistributionSystemType/AirDistribution: DuctLeakageMeasurement[DuctType=\"supply\"]/DuctLeakage[(Units=\"CFM25\" or Units=\"Percent\") and TotalOrToOutside=\"to outside\"]/Value",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution[DistributionSystemType[Other="DSE"]]/AnnualHeatingDistributionSystemEfficiency | AnnualCoolingDistributionSystemEfficiency' => "element 'AnnualHeatingDistributionSystemEfficiency | AnnualCoolingDistributionSystemEfficiency' MUST be greater than or equal to 1",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/DistributionSystemType/AirDistribution/Ducts[DuctType="supply" or DuctType="return"]/DuctInsulationRValue' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/DistributionSystemType/AirDistribution/Ducts[DuctType=\"supply\" or DuctType=\"return\"]: DuctInsulationRValue",
                            '/HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/DistributionSystemType/AirDistribution/Ducts[DuctType="supply" or DuctType="return"]/DuctSurfaceArea | DuctLocation[text()="living space" or text()="basement - conditioned" or text()="basement - unconditioned" or text()="crawlspace - vented" or text()="crawlspace - unvented" or text()="attic - vented" or text()="attic - unvented" or text()="garage" or text()="exterior wall" or text()="under slab" or text()="roof deck" or text()="outside" or text()="other housing unit" or text()="other heated space" or text()="other multifamily buffer space" or text()="other non-freezing space"]' => "Expected [0, 2] element(s) but found 1 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACDistribution/DistributionSystemType/AirDistribution/Ducts[DuctType=\"supply\" or DuctType=\"return\"]: DuctSurfaceArea | DuctLocation[text()=\"living space\" or text()=\"basement - conditioned\" or text()=\"basement - unconditioned\" or text()=\"crawlspace - vented\" or text()=\"crawlspace - unvented\" or text()=\"attic - vented\" or text()=\"attic - unvented\" or text()=\"garage\" or text()=\"exterior wall\" or text()=\"under slab\" or text()=\"roof deck\" or text()=\"outside\" or text()=\"other housing unit\" or text()=\"other heated space\" or text()=\"other multifamily buffer space\" or text()=\"other non-freezing space\"]",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true"]/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation=\"true\"]: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true"]/FanType[text()="energy recovery ventilator" or text()="heat recovery ventilator" or text()="exhaust only" or text()="supply only" or text()="balanced" or text()="central fan integrated supply"]' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation=\"true\"]: FanType[text()=\"energy recovery ventilator\" or text()=\"heat recovery ventilator\" or text()=\"exhaust only\" or text()=\"supply only\" or text()=\"balanced\" or text()=\"central fan integrated supply\"]",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true"]/TestedFlowRate' => "Expected 1 or more element(s) but found 0 elements for xpath: /HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation=\"true\"]: TestedFlowRate | RatedFlowRate",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true"]/HoursInOperation' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation=\"true\"]: HoursInOperation",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true"]/FanPower' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation=\"true\"]: FanPower",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true" and FanType="heat recovery ventilator"]/SensibleRecoveryEfficiency | AdjustedSensibleRecoveryEfficiency' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation=\"true\" and FanType=\"heat recovery ventilator\"]: SensibleRecoveryEfficiency | AdjustedSensibleRecoveryEfficiency",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true" and FanType="energy recovery ventilator"]/TotalRecoveryEfficiency | AdjustedTotalRecoveryEfficiency' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation=\"true\" and FanType=\"energy recovery ventilator\"]: TotalRecoveryEfficiency | AdjustedTotalRecoveryEfficiency",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true" and FanType="energy recovery ventilator"]/SensibleRecoveryEfficiency | AdjustedSensibleRecoveryEfficiency' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation=\"true\" and FanType=\"energy recovery ventilator\"]: SensibleRecoveryEfficiency | AdjustedSensibleRecoveryEfficiency",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation="true" and FanType="central fan integrated supply"]/AttachedToHVACDistributionSystem' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForWholeBuildingVentilation=\"true\" and FanType=\"central fan integrated supply\"]: AttachedToHVACDistributionSystem",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForLocalVentilation="true" and FanLocation="kitchen"]/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForLocalVentilation=\"true\" and FanLocation=\"kitchen\"]: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForLocalVentilation="true" and FanLocation="bath"]/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForLocalVentilation=\"true\" and FanLocation=\"bath\"]: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForSeasonalCoolingLoadReduction="true"]/SystemIdentifier' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForSeasonalCoolingLoadReduction=\"true\"]: SystemIdentifier",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForSeasonalCoolingLoadReduction="true"]/RatedFlowRate' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForSeasonalCoolingLoadReduction=\"true\"]: RatedFlowRate",
                            '/HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForSeasonalCoolingLoadReduction="true"]/FanPower' => "Expected [1] element(s) but found 0 element(s) for xpath: /HPXML/Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFans/VentilationFan[UsedForSeasonalCoolingLoadReduction=\"true\"]: FanPower",
                          }
    
    expected_error_msgs.each do |key, value|
      hpxml_name = get_hpxml_file_name(key)
      hpxml = HPXML.new(hpxml_path: File.join(@root_path, 'workflow', 'sample_files', hpxml_name))
      hpxml_doc = hpxml.to_oga()
      XMLHelper.delete_element(hpxml_doc, key)
      XMLHelper.write_file(hpxml_doc, @tmp_hpxml_path)
      _test_ruby_validation(hpxml_doc, value)
    end
  end

  def _test_schematron_validation(hpxml_path, expected_error_msgs = nil)
    # load the schematron xml
    stron_doc = Nokogiri::XML File.open(File.join(@root_path, 'HPXMLtoOpenStudio', 'resources', 'EPvalidator.xml'))  # "/path/to/schema.stron"
    # make a schematron object
    stron = SchematronNokogiri::Schema.new stron_doc
    # load the xml document you wish to validate
    xml_doc = Nokogiri::XML File.open(hpxml_path)  # "/path/to/xml_document.xml"
    # validate it
    results = stron.validate xml_doc
    # assertions
    if results.empty?
      assert_empty(results)
    else
      assert_equal(expected_error_msgs, results[0][:message])
    end
  end

  def _test_ruby_validation(hpxml_doc, expected_error_msgs = nil)
    # Validate input HPXML against EnergyPlus Use Case
    results = EnergyPlusValidator.run_validator(hpxml_doc)
    if results.empty?
      assert_empty(results)
    else
      assert_equal(expected_error_msgs, results[0])
    end
  end
end